### ISSUE TITLE
rope 0.9.2 reports an unexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by mcepl** [python-rope/ropevim#13]
When I try to do any kind of refactoring with ropevim, I get the following error right after the '//Rope project root folder: .//' prompt.

Opening [.] project ...
{{{
#!python
Error detected while processing function RopeExtractMethod:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ropemode/decorators.py", line 53, in newfunc
    func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/ropemode/interface.py", line 52, in do_refactor
    refactoring(self, self.env).show(initial_asking=initial_asking)
  File "/usr/lib/python2.7/dist-packages/ropemode/refactor.py", line 30, in show
    self.interface._check_project()
  File "/usr/lib/python2.7/dist-packages/ropemode/interface.py", line 406, in _check_project
    self.open_project()
  File "/usr/lib/python2.7/dist-packages/ropemode/decorators.py", line 53, in newfunc
    func(*args, **kwds)
  File "/usr/lib/python2.7/dist-packages/ropemode/interface.py", line 88, in open_project
    self.project = rope.base.project.Project(root)
  File "/usr/lib/python2.7/dist-packages/rope/base/project.py", line 139, in __init__
    fscommands = rope.base.fscommands.create_fscommands(self._address)
  File "/usr/lib/python2.7/dist-packages/rope/base/fscommands.py", line 24, in create_fscommands
    return commands[key](root)
  File "/usr/lib/python2.7/dist-packages/rope/base/fscommands.py", line 87, in __init__
    interactive=False, traceback=False, report_untrusted=False)
TypeError: __init__() got an unexpected keyword argument 'verbose'

}}}

I've downloaded ropevim directly from Bitbucket here: https://bitbucket.org/agr/ropevim

What could be the reason?

**Comment by mcepl** [comment]
I don't know and without a proper reproducer (e.g., what kind of code you were refactoring) we will never find out.

Closing.
