### ISSUE TITLE
Finding Occurrences --- AttributeError: 'Location' object has no attribute 'line_content'

### ISSUE THREAD

**Issue by jean** [python-rope/ropevim#37]
```
0. search
1. cancel
2. batchset
3. unsure
4. in_hierarchy
5. resources
Choose what to do: [search] Find Occurrences ...
Find Occurrences ... 6%%
[...]
Find Occurrences ... 100%%
Find Occurrences ... done
Error detected while processing function RopeFindOccurrences:
line    1:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.linux-i686/egg/ropemode/decorators.py", line 53, in newfunc
  File "build/bdist.linux-i686/egg/ropemode/interface.py", line 257, in find_occurrences
  File "build/bdist.linux-i686/egg/ropemode/interface.py", line 243, in _base_findit
  File "/home/jean/local/lib/python2.7/site-packages/ropevim-0.5.0-py2.7.egg/ropevim.py", line 219, in show_occurrences
    self._quickfixdefs(locations)
  File "/home/jean/local/lib/python2.7/site-packages/ropevim-0.5.0-py2.7.egg/ropevim.py", line 224, in _quickfixdefs
    self._writedefs(locations, filename)
  File "/home/jean/local/lib/python2.7/site-packages/ropevim-0.5.0-py2.7.egg/ropevim.py", line 241, in _writedefs
    location.note, location.line_content)
AttributeError: 'Location' object has no attribute 'line_content'   
```

gvim 7.4

**Comment by luxmeter** [comment]
I have the same issue. Does anyone know what's going wrong?

**Comment by luator** [comment]
Same issue here. Using gVim 7.4 on Ubuntu 12.04, Python 2.7.3.

**Comment by luator** [comment]
I just solved the problem by simply installing the newest version of [ropemode](https://github.com/python-rope/ropemode).

**Comment by thisfred** [comment]
@luator do you mean installing github master of ropemode, or upgrading it through pip? (The latter does not solve this issue for me...)

**Comment by luator** [comment]
@thisfred I installed github master. The important thing is [this commit](https://github.com/python-rope/ropemode/commit/bc4fc73894f54102738fbb071d8332b5cefc3836).

**Comment by thisfred** [comment]
Thanks, that got it working indeed. Time for a pypi release of ropemode then, or a bugfix release of ropevim that works with the released version...

**Comment by mcepl** [comment]
This is strange, but somehow ropemode has not been updated when I took over the maintenance of the package. So, there [0.3](https://pypi.python.org/pypi/ropemode/0.3) now on PyPI. Now, let's see what's going on with `ropevim`.
