### ISSUE TITLE
ValueError when running setup.py

### ISSUE THREAD

**Issue by matmarczak** [python-rope/ropevim#81]
When I run `python setup.py install` on current master I get following exception:

```Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    long_description=get_long_description(),
  File "setup.py", line 28, in get_long_description
    end = lines.index('Setting Up')
ValueError: 'Setting Up' is not in list
```
It works fine with pip though

**Comment by soupytwist** [comment]
Broken in 2539e12, which hasn't been released yet. Thanks for reporting this, will get a fix in shortly.
