### ISSUE TITLE
RopeMoveCurrentModule fails when reloading file

### ISSUE THREAD

**Issue by phubaba** [python-rope/ropevim#88]
During RopeMoveCurrentModule, ropevim.py reload_files is called and subsequently dies if self.filename() is in moves because find_file checks to see if self.filename() exists and of course it doesnt since it has been moved.

initial = self.filename()
....
if initial:
       self.find_file(initial)

one option is to catch exceptions or another option is to extend the if statement to if initial and initial not in moves.

**Comment by eivindjahren** [comment]
I believe I just encountered the same issue, and got the following stacktrace:
```
Error detected while processing function RopeRenameCurrentModule[1]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 3 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "~/.local/lib/python3.10/site-packages/ropemode/decorators.py", line 54, in newfunc
    return func(*args, **kwds)
  File "~/.local/lib/python3.10/site-packages/ropemode/interface.py", line 52, in do_refactor
    refactoring(self, self.env).show(initial_asking=initial_asking)
  File "~/.local/lib/python3.10/site-packages/ropemode/refactor.py", line 45, in show
    self._perform(changes)
  File "~/.local/lib/python3.10/site-packages/ropemode/refactor.py", line 93, in _perform
    runtask(self.env, perform, 'Making %s changes' % self.name,
  File "~/.local/lib/python3.10/site-packages/ropemode/refactor.py", line 469, in runtask
    return RunTask(env, command, name, interrupts)()
  File "~/.local/lib/python3.10/site-packages/ropemode/refactor.py", line 489, in __call__
    result = self.task(handle)
  File "~/.local/lib/python3.10/site-packages/ropemode/refactor.py", line 91, in perform
    self.interface._reload_buffers(changes)
  File "~/.local/lib/python3.10/site-packages/ropemode/interface.py", line 490, in _reload_buffers
    self._reload_buffers_for_changes(
  File "~/.local/lib/python3.10/site-packages/ropemode/interface.py", line 498, in _reload_buffers_for_changes
    self.env.reload_files(filenames, moved)
  File "~/.local/lib/python3.10/site-packages/ropevim.py", line 205, in reload_files
    self.find_file(initial)
  File "~/.local/lib/python3.10/site-packages/ropevim.py", line 248, in find_file
    if self._samefile(win.buffer.name, filename):
  File "~/.local/lib/python3.10/site-packages/ropevim.py", line 222, in _samefile
    return os.path.samefile(file1, file2)
  File "/usr/lib/python3.10/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '~/module_name_before_rename.py'
```

**Comment by eivindjahren** [comment]
This seems related to #77
